### PR TITLE
Update Sapi.php

### PR DESCRIPTION
**Pull request by chakphanu**
ensure $contentLength is integer value.

### CODE REVIEW

**Comment by evert** [comment]
Our of curiosity.. what problem does this solve?

**Comment by chakphanu** [comment]
from: https://github.com/owncloud/core/issues/23788
have error log:  "stream_copy_to_stream() expects parameter 3 to be integer, string given at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#78"

**Comment by evert** [comment]
If the Sapi receives a string with a number in it, this will work just fine. PHP will cast it. The only case that error is triggered is when the received value is *not* a number at all, in which case `intval` will likely turn it to 0, which I think is undesirable.

What should happen is :

1. sabre/http should throw a better error when the value is non-numeric.
2. Find the root-cause of the issue. Why is it getting a non-numeric string?

**Comment by staabm** [comment]
@evert I guess php7 is used with strict types in the above warning/error case

**Comment by evert** [comment]
@staabm , not possible. Strict types are set by the *caller* and strict is off per-file by default. Only if `Sapi.php` was explicitly set to strict, this could have resulted in that error.

**Comment by evert** [comment]
It was never clear what the root cause was for this issue, however.. I've now made a change that fixes this as a side-effect of using PHP 7 strict_types everywhere.

**Comment by rikmeijer** [comment]
In nextcloud problem arises when [downloading files > 2 GB on 32 bit machines](https://github.com/nextcloud/server/issues/1707). In [my comment](https://github.com/nextcloud/server/issues/1707#issuecomment-291835214) I showed a possible fix, but it involves changing sabre/http

**Comment by derkostka** [comment]
@evert please consider taking this change over. This effectively enables owncloud and nextcloud users to be able to transfer large files even on 32 Bit machines. Thanks @rikmeijer 👍

**Pull request closed without merging**
