### PR TITLE
explicitly cast content length to int

### PR DESCRIPTION
**Pull request by icewind1991**
Else the unit tests fail with php7

### CODE REVIEW

**Comment by DanielRuf** [comment]
Not just the unit tests also the output of assets.

**Comment by DanielRuf** [comment]
I wanted to provide the same change. Can you rebase / fix the conflict so the merge can be done?

**Comment by staabm** [comment]
Please rebase/resplve conflicts, atm not mergable as is

**Comment by icewind1991** [comment]
rebased

**Comment by staabm** [comment]
Thx!

**Pull request merged**
